"""add provider profiles

Revision ID: 239c343f2128
Revises: e2235e7ce42d
Create Date: 2026-08-13 22:26:55.689377
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '239c343f2128'
down_revision: Union[str, Sequence[str], None] = 'e2235e7ce42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_profiles',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('adapter', sa.String(length=120), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('secret_binding_ids', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_index(op.f('ix_provider_profiles_tenant_id'), 'provider_profiles', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_profiles_tenant_id'), table_name='provider_profiles')
    op.drop_table('provider_profiles')
    # ### end Alembic commands ###

