"""add telemetry and gate overrides

Revision ID: 50adeaf9b913
Revises: 239c343f2128
Create Date: 2026-08-13 22:49:06.713665
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '50adeaf9b913'
down_revision: Union[str, Sequence[str], None] = '239c343f2128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('span_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('stage', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telemetry_correlation', 'telemetry_events', ['tenant_id', 'correlation_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_correlation_id'), 'telemetry_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_kind'), 'telemetry_events', ['kind'], unique=False)
    op.create_index(op.f('ix_telemetry_events_stage'), 'telemetry_events', ['stage'], unique=False)
    op.create_index(op.f('ix_telemetry_events_status'), 'telemetry_events', ['status'], unique=False)
    op.create_index(op.f('ix_telemetry_events_tenant_id'), 'telemetry_events', ['tenant_id'], unique=False)
    op.create_index('ix_telemetry_tenant_created', 'telemetry_events', ['tenant_id', 'created_at'], unique=False)
    op.create_table('release_gate_overrides',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('gate_id', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('principal_id', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['release_gates.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_gate_overrides_gate_id'), 'release_gate_overrides', ['gate_id'], unique=False)
    op.create_index(op.f('ix_release_gate_overrides_run_id'), 'release_gate_overrides', ['run_id'], unique=False)
    op.create_index(op.f('ix_release_gate_overrides_tenant_id'), 'release_gate_overrides', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_gate_overrides_tenant_id'), table_name='release_gate_overrides')
    op.drop_index(op.f('ix_release_gate_overrides_run_id'), table_name='release_gate_overrides')
    op.drop_index(op.f('ix_release_gate_overrides_gate_id'), table_name='release_gate_overrides')
    op.drop_table('release_gate_overrides')
    op.drop_index('ix_telemetry_tenant_created', table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_tenant_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_status'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_stage'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_kind'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_correlation_id'), table_name='telemetry_events')
    op.drop_index('ix_telemetry_correlation', table_name='telemetry_events')
    op.drop_table('telemetry_events')
    # ### end Alembic commands ###

