"""initial schema

Revision ID: e2235e7ce42d
Revises: 
Create Date: 2026-08-13 22:07:04.356099
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2235e7ce42d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('principal_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('authorization_result', sa.String(length=30), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_principal_id'), 'audit_events', ['principal_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index('ix_audit_resource', 'audit_events', ['tenant_id', 'resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_tenant_created', 'audit_events', ['tenant_id', 'created_at'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('operation', sa.String(length=120), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'operation', 'key')
    )
    op.create_index(op.f('ix_idempotency_keys_tenant_id'), 'idempotency_keys', ['tenant_id'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=120), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('poisoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_correlation_id'), 'outbox', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_outbox_kind'), 'outbox', ['kind'], unique=False)
    op.create_index(op.f('ix_outbox_poisoned_at'), 'outbox', ['poisoned_at'], unique=False)
    op.create_index(op.f('ix_outbox_published_at'), 'outbox', ['published_at'], unique=False)
    op.create_index(op.f('ix_outbox_tenant_id'), 'outbox', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('acl_epoch', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistants',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('active_version_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_index(op.f('ix_assistants_active_version_id'), 'assistants', ['active_version_id'], unique=False)
    op.create_index(op.f('ix_assistants_tenant_id'), 'assistants', ['tenant_id'], unique=False)
    op.create_table('evaluation_datasets',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active_version_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_datasets_active_version_id'), 'evaluation_datasets', ['active_version_id'], unique=False)
    op.create_index(op.f('ix_evaluation_datasets_tenant_id'), 'evaluation_datasets', ['tenant_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_id')
    )
    op.create_index(op.f('ix_groups_tenant_id'), 'groups', ['tenant_id'], unique=False)
    op.create_table('knowledge_spaces',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('default_policy_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_index(op.f('ix_knowledge_spaces_state'), 'knowledge_spaces', ['state'], unique=False)
    op.create_index(op.f('ix_knowledge_spaces_tenant_id'), 'knowledge_spaces', ['tenant_id'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('policy_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'version')
    )
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_versions_tenant_id'), 'policy_versions', ['tenant_id'], unique=False)
    op.create_table('principals',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_id')
    )
    op.create_index(op.f('ix_principals_tenant_id'), 'principals', ['tenant_id'], unique=False)
    op.create_table('release_gates',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metric', sa.String(length=120), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_gates_tenant_id'), 'release_gates', ['tenant_id'], unique=False)
    op.create_table('secret_bindings',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('reference', sa.String(length=1024), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_bindings_tenant_id'), 'secret_bindings', ['tenant_id'], unique=False)
    op.create_table('assistant_versions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('assistant_id', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('knowledge_space_ids', sa.JSON(), nullable=False),
    sa.Column('policy_version_ids', sa.JSON(), nullable=False),
    sa.Column('provider_profile_ids', sa.JSON(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assistant_id', 'version')
    )
    op.create_index(op.f('ix_assistant_versions_assistant_id'), 'assistant_versions', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_assistant_versions_tenant_id'), 'assistant_versions', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('assistant_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_assistant_id'), 'conversations', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('knowledge_space_id', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('secret_binding_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_space_id'], ['knowledge_spaces.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_space_id', 'external_id')
    )
    op.create_index(op.f('ix_data_sources_knowledge_space_id'), 'data_sources', ['knowledge_space_id'], unique=False)
    op.create_index(op.f('ix_data_sources_tenant_id'), 'data_sources', ['tenant_id'], unique=False)
    op.create_table('evaluation_dataset_versions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('dataset_id', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version')
    )
    op.create_index(op.f('ix_evaluation_dataset_versions_dataset_id'), 'evaluation_dataset_versions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_evaluation_dataset_versions_tenant_id'), 'evaluation_dataset_versions', ['tenant_id'], unique=False)
    op.create_table('principal_groups',
    sa.Column('principal_id', sa.String(length=80), nullable=False),
    sa.Column('group_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('principal_id', 'group_id')
    )
    op.create_table('space_memberships',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('knowledge_space_id', sa.String(length=80), nullable=False),
    sa.Column('principal_token', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_space_id'], ['knowledge_spaces.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_space_id', 'principal_token')
    )
    op.create_index(op.f('ix_space_memberships_knowledge_space_id'), 'space_memberships', ['knowledge_space_id'], unique=False)
    op.create_index(op.f('ix_space_memberships_principal_token'), 'space_memberships', ['principal_token'], unique=False)
    op.create_index(op.f('ix_space_memberships_tenant_id'), 'space_memberships', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('knowledge_space_id', sa.String(length=80), nullable=False),
    sa.Column('data_source_id', sa.String(length=80), nullable=False),
    sa.Column('source_identity', sa.String(length=768), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('active_version_id', sa.String(length=80), nullable=True),
    sa.Column('acl_tokens', sa.JSON(), nullable=False),
    sa.Column('acl_epoch', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['knowledge_space_id'], ['knowledge_spaces.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'source_identity')
    )
    op.create_index(op.f('ix_documents_active_version_id'), 'documents', ['active_version_id'], unique=False)
    op.create_index(op.f('ix_documents_data_source_id'), 'documents', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_documents_knowledge_space_id'), 'documents', ['knowledge_space_id'], unique=False)
    op.create_index(op.f('ix_documents_state'), 'documents', ['state'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=80), nullable=False),
    sa.Column('assistant_version_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('evaluator_versions', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('aggregates', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_version_id'], ['assistant_versions.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['evaluation_dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_assistant_version_id'), 'evaluation_runs', ['assistant_version_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_dataset_version_id'), 'evaluation_runs', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_tenant_id'), 'evaluation_runs', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('conversation_id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('query_executions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('conversation_id', sa.String(length=80), nullable=False),
    sa.Column('assistant_version_id', sa.String(length=80), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('component_versions', sa.JSON(), nullable=False),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_version_id'], ['assistant_versions.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_executions_assistant_version_id'), 'query_executions', ['assistant_version_id'], unique=False)
    op.create_index(op.f('ix_query_executions_conversation_id'), 'query_executions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_query_executions_correlation_id'), 'query_executions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_query_executions_tenant_id'), 'query_executions', ['tenant_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('query_id', sa.String(length=80), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['query_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_key', sa.String(length=1024), nullable=False),
    sa.Column('parsed_key', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'content_hash')
    )
    op.create_index(op.f('ix_document_versions_content_hash'), 'document_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_state'), 'document_versions', ['state'], unique=False)
    op.create_index(op.f('ix_document_versions_tenant_id'), 'document_versions', ['tenant_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('item_id', sa.String(length=120), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_item_id'), 'evaluation_results', ['item_id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_run_id'), 'evaluation_results', ['run_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=True),
    sa.Column('document_version_id', sa.String(length=80), nullable=True),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('error_category', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_correlation_id'), 'ingestion_jobs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_document_id'), 'ingestion_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_document_version_id'), 'ingestion_jobs', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_tenant_id'), 'ingestion_jobs', ['tenant_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('knowledge_space_id', sa.String(length=80), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('document_version_id', sa.String(length=80), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=512), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('acl_tokens', sa.JSON(), nullable=False),
    sa.Column('acl_epoch', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['knowledge_space_id'], ['knowledge_spaces.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'ordinal')
    )
    op.create_index(op.f('ix_chunks_active'), 'chunks', ['active'], unique=False)
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_document_version_id'), 'chunks', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_chunks_knowledge_space_id'), 'chunks', ['knowledge_space_id'], unique=False)
    op.create_index(op.f('ix_chunks_tenant_id'), 'chunks', ['tenant_id'], unique=False)
    op.create_table('job_attempts',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('job_id', sa.String(length=80), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_category', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'attempt')
    )
    op.create_index(op.f('ix_job_attempts_job_id'), 'job_attempts', ['job_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('answer_id', sa.String(length=80), nullable=False),
    sa.Column('chunk_id', sa.String(length=120), nullable=False),
    sa.Column('document_version_id', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_answer_id'), 'citations', ['answer_id'], unique=False)
    op.create_index(op.f('ix_citations_chunk_id'), 'citations', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_citations_document_version_id'), 'citations', ['document_version_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('answer_id', sa.String(length=80), nullable=False),
    sa.Column('citation_id', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_answer_id'), 'feedback', ['answer_id'], unique=False)
    op.create_index(op.f('ix_feedback_citation_id'), 'feedback', ['citation_id'], unique=False)
    op.create_index(op.f('ix_feedback_tenant_id'), 'feedback', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_tenant_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_citation_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_answer_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_citations_document_version_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_chunk_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_answer_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_job_attempts_job_id'), table_name='job_attempts')
    op.drop_table('job_attempts')
    op.drop_index(op.f('ix_chunks_tenant_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_knowledge_space_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_version_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_active'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_ingestion_jobs_tenant_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_document_version_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_document_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_correlation_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_evaluation_results_run_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_item_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_document_versions_tenant_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_state'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_content_hash'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_table('answers')
    op.drop_index(op.f('ix_query_executions_tenant_id'), table_name='query_executions')
    op.drop_index(op.f('ix_query_executions_correlation_id'), table_name='query_executions')
    op.drop_index(op.f('ix_query_executions_conversation_id'), table_name='query_executions')
    op.drop_index(op.f('ix_query_executions_assistant_version_id'), table_name='query_executions')
    op.drop_table('query_executions')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_evaluation_runs_tenant_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_dataset_version_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_assistant_version_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_state'), table_name='documents')
    op.drop_index(op.f('ix_documents_knowledge_space_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_data_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_active_version_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_space_memberships_tenant_id'), table_name='space_memberships')
    op.drop_index(op.f('ix_space_memberships_principal_token'), table_name='space_memberships')
    op.drop_index(op.f('ix_space_memberships_knowledge_space_id'), table_name='space_memberships')
    op.drop_table('space_memberships')
    op.drop_table('principal_groups')
    op.drop_index(op.f('ix_evaluation_dataset_versions_tenant_id'), table_name='evaluation_dataset_versions')
    op.drop_index(op.f('ix_evaluation_dataset_versions_dataset_id'), table_name='evaluation_dataset_versions')
    op.drop_table('evaluation_dataset_versions')
    op.drop_index(op.f('ix_data_sources_tenant_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_knowledge_space_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_assistant_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_assistant_versions_tenant_id'), table_name='assistant_versions')
    op.drop_index(op.f('ix_assistant_versions_assistant_id'), table_name='assistant_versions')
    op.drop_table('assistant_versions')
    op.drop_index(op.f('ix_secret_bindings_tenant_id'), table_name='secret_bindings')
    op.drop_table('secret_bindings')
    op.drop_index(op.f('ix_release_gates_tenant_id'), table_name='release_gates')
    op.drop_table('release_gates')
    op.drop_index(op.f('ix_principals_tenant_id'), table_name='principals')
    op.drop_table('principals')
    op.drop_index(op.f('ix_policy_versions_tenant_id'), table_name='policy_versions')
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_knowledge_spaces_tenant_id'), table_name='knowledge_spaces')
    op.drop_index(op.f('ix_knowledge_spaces_state'), table_name='knowledge_spaces')
    op.drop_table('knowledge_spaces')
    op.drop_index(op.f('ix_groups_tenant_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_evaluation_datasets_tenant_id'), table_name='evaluation_datasets')
    op.drop_index(op.f('ix_evaluation_datasets_active_version_id'), table_name='evaluation_datasets')
    op.drop_table('evaluation_datasets')
    op.drop_index(op.f('ix_assistants_tenant_id'), table_name='assistants')
    op.drop_index(op.f('ix_assistants_active_version_id'), table_name='assistants')
    op.drop_table('assistants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_outbox_tenant_id'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_published_at'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_poisoned_at'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_kind'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_correlation_id'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_idempotency_keys_tenant_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_audit_tenant_created', table_name='audit_events')
    op.drop_index('ix_audit_resource', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_principal_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###

